name: Tests
on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: odin test tests/ -all-packages
        timeout-minutes: 1
